version: '3'

services:
  db:
    image: postgres
  redis:
    image: redis
  rabbit:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5673:5672"
  worker:
    build: .
    command: celery -A dashboard worker -l info
    volumes:
      - .:/code
    depends_on:
      - rabbit
      - redis
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - worker
