# Generated by Django 3.0.2 on 2020-01-26 16:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=200)),
                ('interval', models.IntegerField(default=0)),
                ('step', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('marks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('error', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
