# Generated by Django 3.0.2 on 2020-01-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=200)),
                ('interval', models.IntegerField(default=0)),
                ('step', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('error', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
