# Generated by Django 2.2.6 on 2019-11-07 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 20, 36, 31, 607021)),
        ),
    ]
