# Generated by Django 2.2.6 on 2019-11-07 21:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0004_auto_20191107_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 21, 27, 52, 959031, tzinfo=utc)),
        ),
    ]
