# Generated by Django 2.2.6 on 2019-11-07 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0006_auto_20191107_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 21, 30, 4, 460424, tzinfo=utc)),
        ),
    ]
