# Generated by Django 2.2.6 on 2019-11-07 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0007_auto_20191107_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
